# Generated by Django 5.0.4 on 2024-06-02 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_django', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuarios',
            new_name='Usuario',
        ),
        migrations.RemoveField(
            model_name='productos',
            name='categoria',
        ),
        migrations.RenameModel(
            old_name='Clientes',
            new_name='Cliente',
        ),
        migrations.RenameModel(
            old_name='Estados',
            new_name='Estado',
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateField(auto_now=True)),
                ('fecha_pactada', models.DateField()),
                ('fecha_entregada', models.DateField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observaciones', models.TextField(blank=True, max_length=200)),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_django.cliente')),
                ('estado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_django.estado')),
            ],
        ),
        migrations.AlterField(
            model_name='pedido_producto',
            name='pedido',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_django.pedido'),
        ),
        migrations.RenameModel(
            old_name='Categorias',
            new_name='Categoria',
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15)),
                ('descripcion', models.CharField(max_length=30)),
                ('talle', models.CharField(max_length=10)),
                ('color', models.CharField(max_length=15)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad', models.IntegerField()),
                ('cantidad_disponible', models.IntegerField()),
                ('cantidad_limite', models.IntegerField()),
                ('imagen', models.ImageField(blank=True, upload_to='')),
                ('observaciones', models.TextField(blank=True, max_length=200)),
                ('activo', models.IntegerField()),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_django.categoria')),
            ],
        ),
        migrations.AlterField(
            model_name='pedido_producto',
            name='producto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_django.producto'),
        ),
        migrations.DeleteModel(
            name='Pedidos',
        ),
        migrations.DeleteModel(
            name='Productos',
        ),
    ]
