# Generated by Django 5.0.4 on 2024-06-16 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_django', '0004_provincia_localidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localidad',
            name='descripcion',
            field=models.CharField(max_length=50),
        ),
    ]
