# Generated by Django 5.0.4 on 2024-06-17 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_django', '0005_alter_localidad_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localidad',
            name='descripcion',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='provincia',
            name='descripcion',
            field=models.CharField(max_length=50),
        ),
    ]
