# Generated by Django 5.0.4 on 2024-06-17 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_django', '0007_alter_cliente_domicilio_alter_cliente_localidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='localidad',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='provincia',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='localidad',
            name='descripcion',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='provincia',
            name='descripcion',
            field=models.CharField(max_length=60),
        ),
    ]
