# Generated by Django 5.0.4 on 2024-06-18 00:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_django', '0008_alter_cliente_localidad_alter_cliente_provincia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detalle_Envio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domicilio', models.CharField(max_length=60)),
                ('localidad', models.CharField(max_length=80)),
                ('provincia', models.CharField(max_length=60)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True, max_length=200)),
                ('pedido', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_django.pedido')),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_emision', models.DateField(auto_now_add=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado_pago', models.CharField(default='Pendiente', max_length=20)),
                ('metodo_pago', models.CharField(max_length=50)),
                ('observaciones', models.TextField(blank=True, max_length=200)),
                ('pedido', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_django.pedido')),
            ],
        ),
    ]
