# Generated by Django 5.0.4 on 2024-06-24 03:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_django', '0012_alter_categoria_nombre_alter_subcategoria_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='subcategoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_django.subcategoria'),
        ),
    ]
