# Generated by Django 5.0.4 on 2024-07-02 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_django', '0013_producto_subcategoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='talle',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
