# Generated by Django 5.0.4 on 2024-09-22 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_django', '0017_alter_cliente_apellido_alter_cliente_nombre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Talle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10)),
                ('descripcion', models.CharField(max_length=50)),
                ('activo', models.IntegerField()),
            ],
        ),
    ]
