# Generated by Django 5.0.4 on 2024-10-08 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_django', '0019_estadopago_metodopago_alter_factura_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalle_envio',
            name='comentario',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
