# Generated by Django 5.0.4 on 2024-10-13 04:03

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_django', '0020_detalle_envio_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='descuento',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=4),
        ),
    ]
