# Generated by Django 5.0.4 on 2024-11-20 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_django', '0023_factura_descuento_factura_iva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
