# Generated by Django 5.0.4 on 2024-12-02 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_django', '0033_devoluciones_producto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estadodevolucion',
            old_name='estado',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='motivodevolucion',
            old_name='motivo',
            new_name='nombre',
        ),
    ]
