# Generated by Django 5.0.4 on 2024-12-07 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_django', '0034_rename_estado_estadodevolucion_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='devoluciones',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
